version: '2'

services:

  grafana-backup-tool:
    image: zenviavas/grafana-backup-tool:latest
    stdin_open: true
    tty: true
    volumes:
      - ./conf:/app/dashboards_backup/conf:z
      - /tmp:/app/dashboards_backup:z
